parameters:
#    distribuce_tiskudb.example.class: DistribuceTisku\dbBundle\Example

services:
#    distribuce_tiskudb.example:
#        class: %distribuce_tiskudb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
